demo_capture = {
   "demoIndex": 4,
   "demoVersion": "4.f",
   "date": "12/13/2025, 3:45:41 PM",
   "capturedAtFrame": 5051,
   "canvasDimensions": {
      "width": 600,
      "height": 600
   },
   "gravity": false,
   "comSelection": true,
   "fullScreenDemo": false,
   "globalCompositeOperation": "source-over",
   "EpL": {
      "display": true,
      "reportType": "EpL",
      "COM": true,
      "angularAxis_2d_m": {
         "x": 3.2778461538461543,
         "y": 1.5299999999999998
      }
   },
   "wallMapData": {},
   "puckMapData": {
      "puck1": {
         "bullet": false,
         "bulletIndication": false,
         "jello": false,
         "clientName": null,
         "name": "puck1",
         "position_2d_m": {
            "x": 2.04,
            "y": 1.53
         },
         "velocity_2d_mps": {
            "x": 0,
            "y": 0
         },
         "color": "DarkSlateGray",
         "borderColor": "lightgray",
         "shape": "rect",
         "imageID": null,
         "imageScale": 1,
         "colorSource": false,
         "density": 1.5,
         "linDamp": 0,
         "angDamp": 0,
         "createTail": false,
         "tail": null,
         "groupIndex": 0,
         "categoryBits": 1,
         "maskBits": 65535,
         "angle_r": 0,
         "angularSpeed_rps": 0,
         "angleLine": true,
         "borderWidth_px": 3,
         "restitution": 1,
         "restitution_fixed": true,
         "friction": 0,
         "friction_fixed": true,
         "radius_m": 0.24,
         "aspectR": 1,
         "half_height_m": 0.24,
         "half_width_m": 0.24,
         "insideCage": "puck_mf1"
      },
      "puck2": {
         "bullet": false,
         "bulletIndication": false,
         "jello": false,
         "clientName": null,
         "name": "puck2",
         "position_2d_m": {
            "x": 2.64,
            "y": 1.53
         },
         "velocity_2d_mps": {
            "x": 0,
            "y": 0
         },
         "color": "DarkSlateGray",
         "borderColor": "lightgray",
         "shape": "rect",
         "imageID": null,
         "imageScale": 1,
         "colorSource": false,
         "density": 1.5,
         "linDamp": 0,
         "angDamp": 0,
         "createTail": false,
         "tail": null,
         "groupIndex": 0,
         "categoryBits": 1,
         "maskBits": 65535,
         "angle_r": 0,
         "angularSpeed_rps": 0,
         "angleLine": true,
         "borderWidth_px": 3,
         "restitution": 1,
         "restitution_fixed": true,
         "friction": 0,
         "friction_fixed": true,
         "radius_m": 0.24,
         "aspectR": 1,
         "half_height_m": 0.24,
         "half_width_m": 0.24,
         "insideCage": "puck_mf1"
      },
      "puck3": {
         "bullet": false,
         "bulletIndication": false,
         "jello": false,
         "clientName": null,
         "name": "puck3",
         "position_2d_m": {
            "x": 3.24,
            "y": 1.53
         },
         "velocity_2d_mps": {
            "x": 0,
            "y": 0
         },
         "color": "DarkSlateGray",
         "borderColor": "lightgray",
         "shape": "rect",
         "imageID": null,
         "imageScale": 1,
         "colorSource": false,
         "density": 1.5,
         "linDamp": 0,
         "angDamp": 0,
         "createTail": false,
         "tail": null,
         "groupIndex": 0,
         "categoryBits": 1,
         "maskBits": 65535,
         "angle_r": 0,
         "angularSpeed_rps": 0,
         "angleLine": true,
         "borderWidth_px": 3,
         "restitution": 1,
         "restitution_fixed": true,
         "friction": 0,
         "friction_fixed": true,
         "radius_m": 0.24,
         "aspectR": 1,
         "half_height_m": 0.24,
         "half_width_m": 0.24,
         "insideCage": "puck_mf1"
      },
      "puck4": {
         "bullet": false,
         "bulletIndication": false,
         "jello": false,
         "clientName": null,
         "name": "puck4",
         "position_2d_m": {
            "x": 3.84,
            "y": 1.53
         },
         "velocity_2d_mps": {
            "x": 0,
            "y": 0
         },
         "color": "DarkSlateGray",
         "borderColor": "lightgray",
         "shape": "rect",
         "imageID": null,
         "imageScale": 1,
         "colorSource": false,
         "density": 1.5,
         "linDamp": 0,
         "angDamp": 0,
         "createTail": false,
         "tail": null,
         "groupIndex": 0,
         "categoryBits": 1,
         "maskBits": 65535,
         "angle_r": 0,
         "angularSpeed_rps": 0,
         "angleLine": true,
         "borderWidth_px": 3,
         "restitution": 1,
         "restitution_fixed": true,
         "friction": 0,
         "friction_fixed": true,
         "radius_m": 0.24,
         "aspectR": 1,
         "half_height_m": 0.24,
         "half_width_m": 0.24,
         "insideCage": "puck_mf1"
      },
      "puck5": {
         "bullet": false,
         "bulletIndication": false,
         "jello": false,
         "clientName": null,
         "name": "puck5",
         "position_2d_m": {
            "x": 5.2515539363293815,
            "y": 1.53
         },
         "velocity_2d_mps": {
            "x": -1,
            "y": 0
         },
         "color": "DarkSlateGray",
         "borderColor": "lightgray",
         "shape": "rect",
         "imageID": null,
         "imageScale": 1,
         "colorSource": false,
         "density": 1.5,
         "linDamp": 0,
         "angDamp": 0,
         "createTail": false,
         "tail": null,
         "groupIndex": 0,
         "categoryBits": 1,
         "maskBits": 65535,
         "angle_r": 0,
         "angularSpeed_rps": 0,
         "angleLine": true,
         "borderWidth_px": 3,
         "restitution": 1,
         "restitution_fixed": true,
         "friction": 0,
         "friction_fixed": true,
         "radius_m": 0.24,
         "aspectR": 1,
         "half_height_m": 0.24,
         "half_width_m": 0.24,
         "insideCage": "puck_mf1"
      }
   },
   "puckMapData_MultiFix": {
      "puck_mf1": {
         "name": "puck_mf1",
         "position_2d_m": {
            "x": 3.00177939700396,
            "y": 1.53
         },
         "velocity_2d_mps": {
            "x": 0.4499999999999996,
            "y": 0
         },
         "borderWidth_px": 0,
         "density": 1.5,
         "restitution": 1,
         "friction": 0,
         "linDamp": 0,
         "angDamp": 0,
         "angle_r": 0,
         "angularSpeed_rps": 0,
         "groupIndex": 0,
         "categoryBits": 1,
         "maskBits": 65535,
         "type": "cage",
         "cageShape": "rect",
         "legLength_m": 5.4,
         "legThickness_m": 0.04,
         "aspectRatio": 0.1791044776119403,
         "color": "lightgray",
         "borderColor": "DarkSlateGray",
         "balanceOnRestore": true
      }
   },
   "pinMapData": {},
   "springMapData": {},
   "jointMapData": {},
   "startingPosAndVels": [],
   "clients": {
      "local": {
         "color": "tomato",
         "name": "local",
         "ctrlShiftLock": null,
         "poolShotLocked": null,
         "poolShotLockedSpeed_mps": null,
         "bulletAgeLimit_ms": null
      }
   }
}