demo_capture = {
   "demoIndex": 3,
   "demoVersion": "3.d.9ball",
   "date": "5/27/2020, 6:12:48 PM",
   "canvasDimensions": {
      "width": 1915,
      "height": 1075
   },
   "gravity": false,
   "comSelection": true,
   "globalCompositeOperation": "source-over",
   "wallMapData": {
      "wall1": {
         "name": "wall1",
         "position_2d_m": {
            "x": -0.06,
            "y": 5.400000000000002
         },
         "fence": true,
         "fenceLeg": null,
         "velocity_2d_mps": {
            "x": 0,
            "y": 0
         },
         "angle_r": 0,
         "angularSpeed_rps": 0,
         "half_width_m": 4.31,
         "half_height_m": 0.06,
         "color": "lightgray"
      },
      "wall2": {
         "name": "wall2",
         "position_2d_m": {
            "x": 19.19,
            "y": 5.3400000000000105
         },
         "fence": true,
         "fenceLeg": null,
         "velocity_2d_mps": {
            "x": 0,
            "y": 0
         },
         "angle_r": 0,
         "angularSpeed_rps": 0,
         "half_width_m": 4.31,
         "half_height_m": 0.06,
         "color": "lightgray"
      },
      "wall5": {
         "name": "wall5",
         "position_2d_m": {
            "x": 4.915000000000001,
            "y": 10.79000000000001
         },
         "fence": true,
         "fenceLeg": null,
         "velocity_2d_mps": {
            "x": 0,
            "y": 0
         },
         "angle_r": 0,
         "angularSpeed_rps": 0,
         "half_width_m": 3.77,
         "half_height_m": 0.06,
         "color": "lightgray"
      },
      "wall6": {
         "name": "wall6",
         "position_2d_m": {
            "x": 14.209999999999994,
            "y": 10.78
         },
         "fence": true,
         "fenceLeg": "top",
         "velocity_2d_mps": {
            "x": 0,
            "y": 0
         },
         "angle_r": 0,
         "angularSpeed_rps": 0,
         "half_width_m": 3.77,
         "half_height_m": 0.06,
         "color": "lightgray"
      },
      "wall10": {
         "name": "wall10",
         "position_2d_m": {
            "x": 4.93,
            "y": -0.04
         },
         "fence": true,
         "fenceLeg": null,
         "velocity_2d_mps": {
            "x": 0,
            "y": 0
         },
         "angle_r": 0,
         "angularSpeed_rps": 0,
         "half_width_m": 3.77,
         "half_height_m": 0.06,
         "color": "lightgray"
      },
      "wall11": {
         "name": "wall11",
         "position_2d_m": {
            "x": 14.190000000000005,
            "y": -0.04
         },
         "fence": true,
         "fenceLeg": null,
         "velocity_2d_mps": {
            "x": 0,
            "y": 0
         },
         "angle_r": 0,
         "angularSpeed_rps": 0,
         "half_width_m": 3.77,
         "half_height_m": 0.06,
         "color": "lightgray"
      }
   },
   "puckMapData": {
      "puck1": {
         "bullet": true,
         "atLeastOneHit": false,
         "jello": false,
         "clientName": null,
         "name": "puck1",
         "nameTip_timerLimit_s": 2,
         "nameTip_timer_s": 0,
         "position_2d_m": {
            "x": 4.921975085132408,
            "y": 5.347212952189928
         },
         "velocity_2d_mps": {
            "x": 0,
            "y": 0
         },
         "color": "yellow",
         "shape": "circle",
         "colorSource": true,
         "density": 1.5,
         "linDamp": 0.5,
         "angDamp": 0,
         "hitLimit": 10,
         "createTail": false,
         "tailPars": null,
         "groupIndex": 0,
         "categoryBits": 1,
         "maskBits": 65535,
         "angle_r": -14.850862997521132,
         "angularSpeed_rps": 0,
         "angleLine": false,
         "borderWidth_px": 0,
         "restitution": 1,
         "restitution_fixed": false,
         "friction": 0,
         "friction_fixed": true,
         "radius_m": 0.35,
         "aspectR": 1,
         "half_height_m": null,
         "half_width_m": null
      },
      "puck8": {
         "bullet": true,
         "atLeastOneHit": false,
         "jello": false,
         "clientName": null,
         "name": "puck8",
         "nameTip_timerLimit_s": 2,
         "nameTip_timer_s": 0,
         "position_2d_m": {
            "x": 3.038968841365974,
            "y": 5.011167290391769
         },
         "velocity_2d_mps": {
            "x": 0,
            "y": 0
         },
         "color": "black",
         "shape": "circle",
         "colorSource": true,
         "density": 1.5,
         "linDamp": 0.5,
         "angDamp": 0,
         "hitLimit": 10,
         "createTail": false,
         "tailPars": null,
         "groupIndex": 0,
         "categoryBits": 1,
         "maskBits": 65535,
         "angle_r": -14.850897892323893,
         "angularSpeed_rps": 0,
         "angleLine": false,
         "borderWidth_px": 0,
         "restitution": 1,
         "restitution_fixed": false,
         "friction": 0,
         "friction_fixed": true,
         "radius_m": 0.35,
         "aspectR": 1,
         "half_height_m": null,
         "half_width_m": null
      },
      "puck9": {
         "bullet": true,
         "atLeastOneHit": false,
         "jello": false,
         "clientName": null,
         "name": "puck9",
         "nameTip_timerLimit_s": 2,
         "nameTip_timer_s": 0,
         "position_2d_m": {
            "x": 3.6737578137425553,
            "y": 5.341033832358266
         },
         "velocity_2d_mps": {
            "x": 0,
            "y": 0
         },
         "color": "yellow",
         "shape": "circle",
         "colorSource": true,
         "density": 1.5,
         "linDamp": 0.5,
         "angDamp": 0,
         "hitLimit": 10,
         "createTail": false,
         "tailPars": null,
         "groupIndex": 0,
         "categoryBits": 1,
         "maskBits": 65535,
         "angle_r": -14.850897892323868,
         "angularSpeed_rps": 0,
         "angleLine": false,
         "borderWidth_px": 0,
         "restitution": 1,
         "restitution_fixed": false,
         "friction": 0,
         "friction_fixed": true,
         "radius_m": 0.35,
         "aspectR": 1,
         "half_height_m": null,
         "half_width_m": null
      },
      "puck2": {
         "bullet": true,
         "atLeastOneHit": false,
         "jello": false,
         "clientName": null,
         "name": "puck2",
         "nameTip_timerLimit_s": 2,
         "nameTip_timer_s": 0,
         "position_2d_m": {
            "x": 3.6737578126168646,
            "y": 6.036033832358262
         },
         "velocity_2d_mps": {
            "x": 0,
            "y": 0
         },
         "color": "blue",
         "shape": "circle",
         "colorSource": true,
         "density": 1.5,
         "linDamp": 0.5,
         "angDamp": 0,
         "hitLimit": 10,
         "createTail": false,
         "tailPars": null,
         "groupIndex": 0,
         "categoryBits": 1,
         "maskBits": 65535,
         "angle_r": -14.850897892323882,
         "angularSpeed_rps": 0,
         "angleLine": false,
         "borderWidth_px": 0,
         "restitution": 1,
         "restitution_fixed": false,
         "friction": 0,
         "friction_fixed": true,
         "radius_m": 0.35,
         "aspectR": 1,
         "half_height_m": null,
         "half_width_m": null
      },
      "puck3": {
         "bullet": true,
         "atLeastOneHit": false,
         "jello": false,
         "clientName": null,
         "name": "puck3",
         "nameTip_timerLimit_s": 2,
         "nameTip_timer_s": 0,
         "position_2d_m": {
            "x": 2.421914226095024,
            "y": 5.37482252629946
         },
         "velocity_2d_mps": {
            "x": 0,
            "y": 0
         },
         "color": "red",
         "shape": "circle",
         "colorSource": true,
         "density": 1.5,
         "linDamp": 0.5,
         "angDamp": 0,
         "hitLimit": 10,
         "createTail": false,
         "tailPars": null,
         "groupIndex": 0,
         "categoryBits": 1,
         "maskBits": 65535,
         "angle_r": -14.877061374732094,
         "angularSpeed_rps": 0,
         "angleLine": false,
         "borderWidth_px": 0,
         "restitution": 1,
         "restitution_fixed": false,
         "friction": 0,
         "friction_fixed": true,
         "radius_m": 0.35,
         "aspectR": 1,
         "half_height_m": null,
         "half_width_m": null
      },
      "puck4": {
         "bullet": true,
         "atLeastOneHit": false,
         "jello": false,
         "clientName": null,
         "name": "puck4",
         "nameTip_timerLimit_s": 2,
         "nameTip_timer_s": 0,
         "position_2d_m": {
            "x": 3.6737578147625216,
            "y": 4.646033832358268
         },
         "velocity_2d_mps": {
            "x": 0,
            "y": 0
         },
         "color": "purple",
         "shape": "circle",
         "colorSource": true,
         "density": 1.5,
         "linDamp": 0.5,
         "angDamp": 0,
         "hitLimit": 10,
         "createTail": false,
         "tailPars": null,
         "groupIndex": 0,
         "categoryBits": 1,
         "maskBits": 65535,
         "angle_r": -14.85089789232389,
         "angularSpeed_rps": 0,
         "angleLine": false,
         "borderWidth_px": 0,
         "restitution": 1,
         "restitution_fixed": false,
         "friction": 0,
         "friction_fixed": true,
         "radius_m": 0.35,
         "aspectR": 1,
         "half_height_m": null,
         "half_width_m": null
      },
      "puck5": {
         "bullet": true,
         "atLeastOneHit": false,
         "jello": false,
         "clientName": null,
         "name": "puck5",
         "nameTip_timerLimit_s": 2,
         "nameTip_timer_s": 0,
         "position_2d_m": {
            "x": 4.314478597546679,
            "y": 5.694594091409944
         },
         "velocity_2d_mps": {
            "x": 0,
            "y": 0
         },
         "color": "orange",
         "shape": "circle",
         "colorSource": true,
         "density": 1.5,
         "linDamp": 0.5,
         "angDamp": 0,
         "hitLimit": 10,
         "createTail": false,
         "tailPars": null,
         "groupIndex": 0,
         "categoryBits": 1,
         "maskBits": 65535,
         "angle_r": -14.85089789232389,
         "angularSpeed_rps": 0,
         "angleLine": false,
         "borderWidth_px": 0,
         "restitution": 1,
         "restitution_fixed": false,
         "friction": 0,
         "friction_fixed": true,
         "radius_m": 0.35,
         "aspectR": 1,
         "half_height_m": null,
         "half_width_m": null
      },
      "puck6": {
         "bullet": true,
         "atLeastOneHit": false,
         "jello": false,
         "clientName": null,
         "name": "puck6",
         "nameTip_timerLimit_s": 2,
         "nameTip_timer_s": 0,
         "position_2d_m": {
            "x": 4.314478597546679,
            "y": 4.999594091409948
         },
         "velocity_2d_mps": {
            "x": 0,
            "y": 0
         },
         "color": "green",
         "shape": "circle",
         "colorSource": true,
         "density": 1.5,
         "linDamp": 0.5,
         "angDamp": 0,
         "hitLimit": 10,
         "createTail": false,
         "tailPars": null,
         "groupIndex": 0,
         "categoryBits": 1,
         "maskBits": 65535,
         "angle_r": -16.849287056492393,
         "angularSpeed_rps": 0,
         "angleLine": false,
         "borderWidth_px": 0,
         "restitution": 1,
         "restitution_fixed": false,
         "friction": 0,
         "friction_fixed": true,
         "radius_m": 0.35,
         "aspectR": 1,
         "half_height_m": null,
         "half_width_m": null
      },
      "puck7": {
         "bullet": true,
         "atLeastOneHit": false,
         "jello": false,
         "clientName": null,
         "name": "puck7",
         "nameTip_timerLimit_s": 2,
         "nameTip_timer_s": 0,
         "position_2d_m": {
            "x": 3.0389688413688587,
            "y": 5.706167290391765
         },
         "velocity_2d_mps": {
            "x": 0,
            "y": 0
         },
         "color": "#800020",
         "shape": "circle",
         "colorSource": true,
         "density": 1.5,
         "linDamp": 0.5,
         "angDamp": 0,
         "hitLimit": 10,
         "createTail": false,
         "tailPars": null,
         "groupIndex": 0,
         "categoryBits": 1,
         "maskBits": 65535,
         "angle_r": -14.850897892323882,
         "angularSpeed_rps": 0,
         "angleLine": false,
         "borderWidth_px": 0,
         "restitution": 1,
         "restitution_fixed": false,
         "friction": 0,
         "friction_fixed": true,
         "radius_m": 0.35,
         "aspectR": 1,
         "half_height_m": null,
         "half_width_m": null
      },
      "puck0": {
         "bullet": true,
         "atLeastOneHit": false,
         "jello": false,
         "clientName": null,
         "name": "puck0",
         "nameTip_timerLimit_s": 2,
         "nameTip_timer_s": 0,
         "position_2d_m": {
            "x": 14.242822009634374,
            "y": 5.404883202184683
         },
         "velocity_2d_mps": {
            "x": 0,
            "y": 0
         },
         "color": "lightgray",
         "shape": "circle",
         "colorSource": true,
         "density": 1.5,
         "linDamp": 0.5,
         "angDamp": 0,
         "hitLimit": 10,
         "createTail": false,
         "tailPars": null,
         "groupIndex": 0,
         "categoryBits": 1,
         "maskBits": 65535,
         "angle_r": -13.54640630097413,
         "angularSpeed_rps": 0,
         "angleLine": false,
         "borderWidth_px": 0,
         "restitution": 1,
         "restitution_fixed": false,
         "friction": 0,
         "friction_fixed": true,
         "radius_m": 0.35,
         "aspectR": 1,
         "half_height_m": null,
         "half_width_m": null
      }
   },
   "pinMapData": {},
   "springMapData": {},
   "startingPosAndVels": [],
   "clients": {
      "local": {
         "color": "tomato",
         "name": "local",
         "player": true,
         "nickName": null,
         "NPC_pin_timer_s": 0,
         "NPC_pin_timer_limit_s": 5,
         "ctrlShiftLock": true,
         "poolShotLocked": true,
         "poolShotLockedSpeed_mps": 20         
      }
   }
}